// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_theme_showcase/test/presentation/blocs/localization_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i10;

import 'package:dartz/dartz.dart' as _i3;
import 'package:flutter_theme_showcase/core/errors/failures.dart' as _i6;
import 'package:flutter_theme_showcase/domain/entities/localization_entity.dart'
    as _i7;
import 'package:flutter_theme_showcase/domain/repositories/localization_repository.dart'
    as _i2;
import 'package:flutter_theme_showcase/domain/use_cases/localization/get_current_localization_use_case.dart'
    as _i4;
import 'package:flutter_theme_showcase/domain/use_cases/localization/get_supported_localizations_use_case.dart'
    as _i8;
import 'package:flutter_theme_showcase/domain/use_cases/localization/switch_localization_use_case.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLocalizationRepository_0 extends _i1.SmartFake
    implements _i2.LocalizationRepository {
  _FakeLocalizationRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetCurrentLocalizationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentLocalizationUseCase extends _i1.Mock
    implements _i4.GetCurrentLocalizationUseCase {
  MockGetCurrentLocalizationUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LocalizationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeLocalizationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.LocalizationRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.LocalizationEntity>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.LocalizationEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.LocalizationEntity>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.LocalizationEntity>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> getCurrentLocaleString() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentLocaleString,
          [],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
            _FakeEither_1<_i6.Failure, String>(
          this,
          Invocation.method(
            #getCurrentLocaleString,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, String>>);
}

/// A class which mocks [GetSupportedLocalizationsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSupportedLocalizationsUseCase extends _i1.Mock
    implements _i8.GetSupportedLocalizationsUseCase {
  MockGetSupportedLocalizationsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LocalizationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeLocalizationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.LocalizationRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.LocalizationEntity>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<
                _i3.Either<_i6.Failure, List<_i7.LocalizationEntity>>>.value(
            _FakeEither_1<_i6.Failure, List<_i7.LocalizationEntity>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.LocalizationEntity>>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.LocalizationEntity?>>
      getDefaultLocalization() => (super.noSuchMethod(
            Invocation.method(
              #getDefaultLocalization,
              [],
            ),
            returnValue: _i5
                .Future<_i3.Either<_i6.Failure, _i7.LocalizationEntity?>>.value(
                _FakeEither_1<_i6.Failure, _i7.LocalizationEntity?>(
              this,
              Invocation.method(
                #getDefaultLocalization,
                [],
              ),
            )),
          ) as _i5.Future<_i3.Either<_i6.Failure, _i7.LocalizationEntity?>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.LocalizationEntity>>>
      getRtlLocalizations() => (super.noSuchMethod(
            Invocation.method(
              #getRtlLocalizations,
              [],
            ),
            returnValue: _i5.Future<
                    _i3
                    .Either<_i6.Failure, List<_i7.LocalizationEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.LocalizationEntity>>(
              this,
              Invocation.method(
                #getRtlLocalizations,
                [],
              ),
            )),
          ) as _i5
              .Future<_i3.Either<_i6.Failure, List<_i7.LocalizationEntity>>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<String>>> getLanguageCodes() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLanguageCodes,
          [],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, List<String>>>.value(
            _FakeEither_1<_i6.Failure, List<String>>(
          this,
          Invocation.method(
            #getLanguageCodes,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<String>>>);
}

/// A class which mocks [SwitchLocalizationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSwitchLocalizationUseCase extends _i1.Mock
    implements _i9.SwitchLocalizationUseCase {
  MockSwitchLocalizationUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LocalizationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeLocalizationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.LocalizationRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.LocalizationEntity>> call(
          String? localeString) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [localeString],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.LocalizationEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.LocalizationEntity>(
          this,
          Invocation.method(
            #call,
            [localeString],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.LocalizationEntity>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.LocalizationEntity>> callWithLocale(
          _i10.Locale? locale) =>
      (super.noSuchMethod(
        Invocation.method(
          #callWithLocale,
          [locale],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.LocalizationEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.LocalizationEntity>(
          this,
          Invocation.method(
            #callWithLocale,
            [locale],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.LocalizationEntity>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.LocalizationEntity>>
      switchToEnglish() => (super.noSuchMethod(
            Invocation.method(
              #switchToEnglish,
              [],
            ),
            returnValue: _i5
                .Future<_i3.Either<_i6.Failure, _i7.LocalizationEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.LocalizationEntity>(
              this,
              Invocation.method(
                #switchToEnglish,
                [],
              ),
            )),
          ) as _i5.Future<_i3.Either<_i6.Failure, _i7.LocalizationEntity>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.LocalizationEntity>>
      switchToVietnamese() => (super.noSuchMethod(
            Invocation.method(
              #switchToVietnamese,
              [],
            ),
            returnValue: _i5
                .Future<_i3.Either<_i6.Failure, _i7.LocalizationEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.LocalizationEntity>(
              this,
              Invocation.method(
                #switchToVietnamese,
                [],
              ),
            )),
          ) as _i5.Future<_i3.Either<_i6.Failure, _i7.LocalizationEntity>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.LocalizationEntity>>
      switchToSystemLocale() => (super.noSuchMethod(
            Invocation.method(
              #switchToSystemLocale,
              [],
            ),
            returnValue: _i5
                .Future<_i3.Either<_i6.Failure, _i7.LocalizationEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.LocalizationEntity>(
              this,
              Invocation.method(
                #switchToSystemLocale,
                [],
              ),
            )),
          ) as _i5.Future<_i3.Either<_i6.Failure, _i7.LocalizationEntity>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.LocalizationEntity>>
      resetToDefault() => (super.noSuchMethod(
            Invocation.method(
              #resetToDefault,
              [],
            ),
            returnValue: _i5
                .Future<_i3.Either<_i6.Failure, _i7.LocalizationEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.LocalizationEntity>(
              this,
              Invocation.method(
                #resetToDefault,
                [],
              ),
            )),
          ) as _i5.Future<_i3.Either<_i6.Failure, _i7.LocalizationEntity>>);
}
