name: flutter_theme_showcase
description: A Flutter theme showcase app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_screenutil: ^5.9.3
  objectbox: ^2.5.1
  objectbox_flutter_libs: ^2.5.1
  get_it: ^7.6.4
  injectable: ^2.3.2

dev_dependencies:
  bloc_test: ^9.1.7
  objectbox_generator: ^2.5.1
  build_runner: ^2.4.6
  injectable_generator: ^2.4.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
