name: flutter_theme_showcase
description: A Flutter theme showcase app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

