name: flutter_theme_showcase
description: A Flutter theme showcase app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  # Clean Architecture dependencies
  bloc: ^8.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  google_fonts: ^6.3.0
  injectable: ^2.3.2
  intl: ^0.20.2
  json_annotation: ^4.8.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  # Code generation dependencies
  bloc_test: ^9.1.5
  build_runner: ^2.4.7
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  generate: true
