// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_theme_showcase/test/domain/use_cases/switch_localization_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i7;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_theme_showcase/core/errors/failures.dart' as _i5;
import 'package:flutter_theme_showcase/domain/entities/localization_entity.dart'
    as _i6;
import 'package:flutter_theme_showcase/domain/repositories/localization_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocalizationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalizationRepository extends _i1.Mock
    implements _i3.LocalizationRepository {
  MockLocalizationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.LocalizationEntity>>
      getCurrentLocalization() => (super.noSuchMethod(
            Invocation.method(
              #getCurrentLocalization,
              [],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, _i6.LocalizationEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.LocalizationEntity>(
              this,
              Invocation.method(
                #getCurrentLocalization,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.LocalizationEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.LocalizationEntity>>>
      getSupportedLocalizations() => (super.noSuchMethod(
            Invocation.method(
              #getSupportedLocalizations,
              [],
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i6.LocalizationEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.LocalizationEntity>>(
              this,
              Invocation.method(
                #getSupportedLocalizations,
                [],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i6.LocalizationEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> setCurrentLocalization(
          _i7.Locale? locale) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCurrentLocalization,
          [locale],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #setCurrentLocalization,
            [locale],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.LocalizationEntity>>
      getLocalizationByLocale(_i7.Locale? locale) => (super.noSuchMethod(
            Invocation.method(
              #getLocalizationByLocale,
              [locale],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, _i6.LocalizationEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.LocalizationEntity>(
              this,
              Invocation.method(
                #getLocalizationByLocale,
                [locale],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.LocalizationEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> isLocaleSupported(
          _i7.Locale? locale) =>
      (super.noSuchMethod(
        Invocation.method(
          #isLocaleSupported,
          [locale],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #isLocaleSupported,
            [locale],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.Locale>> getSystemLocale() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSystemLocale,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i7.Locale>>.value(
            _FakeEither_0<_i5.Failure, _i7.Locale>(
          this,
          Invocation.method(
            #getSystemLocale,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.Locale>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> resetToDefaultLocale() =>
      (super.noSuchMethod(
        Invocation.method(
          #resetToDefaultLocale,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #resetToDefaultLocale,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.Locale?>> getSavedLocale() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSavedLocale,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i7.Locale?>>.value(
            _FakeEither_0<_i5.Failure, _i7.Locale?>(
          this,
          Invocation.method(
            #getSavedLocale,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.Locale?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> saveLocalePreference(
          _i7.Locale? locale) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLocalePreference,
          [locale],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #saveLocalePreference,
            [locale],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> clearLocalePreference() =>
      (super.noSuchMethod(
        Invocation.method(
          #clearLocalePreference,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #clearLocalePreference,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
